package com.enigmabridge.comm;

import com.enigmabridge.UserObjectInfo;

import java.io.Serializable;

/**
 * Request generated by the request builder.
 * Created by dusanklinec on 27.04.16.
 */
public class EBProcessDataRequest implements Serializable {
    public static final long serialVersionUID = 1L;
    
    protected byte[] nonce;
    protected UserObjectInfo uo;

    protected byte[] requestBody;

    /**
     * Main request part.
     * Mandatory.
     */
    protected String request;

    public EBProcessDataRequest(String request) {
        this.request = request;
    }

    public EBProcessDataRequest(String request, byte[] requestBody, UserObjectInfo uo, byte[] nonce) {
        this.request = request;
        this.requestBody = requestBody;
        this.uo = uo;
        this.nonce = nonce;
    }

    public byte[] getNonce() {
        return nonce;
    }

    void setNonce(byte[] nonce) {
        this.nonce = nonce;
    }

    public UserObjectInfo getUo() {
        return uo;
    }

    void setUo(UserObjectInfo uo) {
        this.uo = uo;
    }

    public byte[] getRequestBody() {
        return requestBody;
    }

    void setRequestBody(byte[] requestBody) {
        this.requestBody = requestBody;
    }

    public String getRequest() {
        return request;
    }

    void setRequest(String request) {
        this.request = request;
    }
}
